version: 2

jobs:
  build:
    working_directory: ~/aptitude-cracker

    docker:
      - image: circleci/android:api-26

    environment:
      ANDROID_HOME: /opt/android/sdk
      ANDROID_BUILD_TOOLS: 26.0.0
      APPLICATION_ID: com.droidacid.apticalc
#      FABRIC_API_KEY: 0000000000000000000000000000000000000000
#      GOOGLE_MAPS_API_KEY: DUMMY_GOOGLE_MAPS_API_KEY
#      NEARIT_API_KEY: DUMMY_NEARIT_API_KEY
#      TWITTER_API_KEY: DUMMY_TWITTER_API_KEY
#      TWITTER_SECRET: DUMMY_TWITTER_SECRET

    steps:
      - checkout

      # Restore cached dependencies (if any)
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # Prepare the container for the build
      - run:
          name: Accept Android SDK license
          command: .circleci/ci-scripts/accept-android-licenses.sh
      - run:
          name: Ensure Android SDK install is up-to-date
          command: .circleci/ci-scripts/ensure-sdkmanager.sh

      # Run the main job command, delegating to Gradle
      - run:
          name: Run Gradle :check command
          command: ./gradlew check --continue

      # Store all the downloaded dependencies in the CI cache
      - save_cache:
          paths:
            # Android SDK
            - /usr/local/android-sdk-linux/tools
            - /usr/local/android-sdk-linux/platform-tools
            - /usr/local/android-sdk-linux/build-tools
            - /usr/local/android-sdk-linux/licenses
            - /usr/local/android-sdk-linux/extras/google/m2repository

            # Gradle dependencies
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # Collect static analysis reports as build artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Collect JUnit test results
      - store_test_results:
          path: app/build/test-results
